root: true
globals:
  ClipboardJS: readonly
  notify: readonly
env:
  browser: true
  node: true
  es6: true
  webextensions: true
parserOptions:
  ecmaVersion: 2019
plugins:
  - prettier
rules:
  prettier/prettier: error
extends:
  - eslint:recommended
  - prettier
